name: Manifest and schemas

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions: {}

jobs:

  check-manifest:
    name: "Manifest / python ${{ matrix.python-version }}"
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13", "3.14"]

    steps:
      - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98
        with:
          persist-credentials: false

      - uses: actions/setup-python@28f2168f4d98ee0445e3c6321f6e6616c83dd5ec
        with:
          python-version: ${{ matrix.python-version }}

      - uses: astral-sh/setup-uv@5c62c5926145985eec91f09e2e0a75f40daed929
        with:
          version: "0.10.2"
          enable-cache: true

      - run: uv sync --frozen

      - run: uv run --no-sync --frozen fractal-manifest check --package example-tasks

  check-single-schemas:
    name: Single JSON schemas
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98
        with:
          persist-credentials: false

      - uses: actions/setup-python@28f2168f4d98ee0445e3c6321f6e6616c83dd5ec
        with:
          python-version: "3.12"

      - uses: astral-sh/setup-uv@5c62c5926145985eec91f09e2e0a75f40daed929
        with:
          version: "0.10.2"
          enable-cache: true

      - run: uv sync --frozen

      - run: uv run --no-sync --frozen ./single_json_schemas/extract.py

      - run: git diff --exit-code ./single_json_schemas
