name: Check manifest

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions: {}

jobs:

  check-manifest:
    name: "Python ${{ matrix.python-version }}"
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13", "3.14"]

    steps:   
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - uses: astral-sh/setup-uv@v7
        with:
          version: "0.10.2"
          enable-cache: true

      - run: uv sync --frozen
      - run: uv run --no-sync --frozen fractal-manifest check --package example-tasks

  check-single-schemas:
    name: Check single JSON schemas
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    needs:
      - check-manifest

    steps:   
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - uses: astral-sh/setup-uv@v7
        with:
          version: "0.10.2"
          enable-cache: true

      - run: uv sync --frozen

      - run: uv run --no-sync --frozen ./single_json_schemas/extract.py

      - run: git diff --exit-code ./single_json_schemas